name: thrift_books
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  list_tile_switch: ^1.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  flutter_staggered_grid_view: ^0.4.0
  badges: ^2.0.1
  backdrop: ^0.6.1
  carousel_pro: ^1.0.0
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - android/assets/images/emptycart.png
    - android/assets/images/empty_cart.png
    - android/assets/images/b1.jpg
    - android/assets/images/b2.jpg
    - android/assets/images/b3.jpg
    - android/assets/images/b4.jpg
    - android/assets/images/book1.jpg
    - android/assets/images/book2.jpg
    - android/assets/images/book3.jpg
    - android/assets/images/book4.jpg
    - android/assets/images/geo.jpg
    - android/assets/images/history.jpg
    - android/assets/images/maths.jpg
    - android/assets/images/sci.jpg
    - android/assets/images/space.jpg
    - android/assets/images/eng.jpg
    - android/assets/images/lawyer.jpg
    - android/assets/images/scientist.jpg
    - android/assets/images/police.jpg
    - android/assets/images/wishlist_empty.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
